@startuml
'https://plantuml.com/component-diagram

skinparam component {
  backgroundColor<<Global>> LightGray
  backgroundColor<<InAdapter>> LightGreen
  backgroundColor<<Service>> LightBlue
  backgroundColor<<OutAdapter>> LightYellow
}

component extension.ts <<Global>> {
    component CustomTextEditor
}
component "IoC-Container" <<Global>>

component "WebviewAdapter" as InWebviewAdapter <<InAdapter>>
component "DocumentAdapter" as InDocumentAdapter <<InAdapter>>
component "TextEditorAdapter" as InTextEditorAdapter <<InAdapter>>

component {
    portin InitWebviewUseCase
    portin SyncWebviewUseCase
    portin SyncDocumentUseCase
    portin TextEditorUseCase

    portout DocumentPort
    portout WebviewPort
    portout TextEditorPort

    component InitWebviewService <<Service>>
    component SyncWebviewService <<Service>>
    component SyncDocumentService <<Service>>
    component TextEditorService <<Service>>
}

component "WebviewAdapter" as OutWebviewAdapter <<OutAdapter>>
component "DocumentAdapter" as OutDocumentAdapter <<OutAdapter>>
component "TextEditorAdapter" as OutTextEditorAdapter <<OutAdapter>>

extension.ts --> InTextEditorAdapter : create
CustomTextEditor --> InWebviewAdapter : create
CustomTextEditor --> InDocumentAdapter : create
CustomTextEditor --> OutWebviewAdapter : set active webview
CustomTextEditor --> OutDocumentAdapter : set active document

InWebviewAdapter --> InitWebviewUseCase
InWebviewAdapter --> SyncDocumentUseCase
InDocumentAdapter --> SyncWebviewUseCase
InTextEditorAdapter --> TextEditorUseCase

InitWebviewUseCase <.. InitWebviewService
SyncWebviewUseCase <.. SyncWebviewService
SyncDocumentUseCase <.. SyncDocumentService
TextEditorUseCase <.. TextEditorService

InitWebviewService --> WebviewPort
SyncWebviewService --> WebviewPort
SyncDocumentService --> DocumentPort
TextEditorService --> TextEditorPort

WebviewPort <.. OutWebviewAdapter
DocumentPort <.. OutDocumentAdapter
TextEditorPort <.. OutTextEditorAdapter

OutTextEditorAdapter --> OutDocumentAdapter : get active document

@enduml
