@startuml
'https://plantuml.com/component-diagram

skinparam component {
  backgroundColor<<Global>> LightGray
  backgroundColor<<In Adapter>> LightGreen
  backgroundColor<<Service>> LightBlue
  backgroundColor<<Out Adapter>> LightYellow
}

component extension.ts <<Global>>
component "IoC-Container" <<Global>>

component "WebviewAdapter" as InWebviewAdapter <<In Adapter>>
component "DocumentAdapter" as InDocumentAdapter <<In Adapter>>
component "TextEditorAdapter" as InTextEditorAdapter <<In Adapter>>

component {
    portin InitWebviewUseCase
    portin SyncWebviewUseCase
    portin SyncDocumentUseCase
    portin TextEditorUseCase

    portout DocumentPort
    portout WebviewPort
    portout TextEditorPort
    portout LoggerPort

    component InitWebviewService <<Service>>
    component SyncWebviewService <<Service>>
    component SyncDocumentService <<Service>>
    component TextEditorService <<Service>>
}

component "WebviewAdapter" as OutWebviewAdapter <<Out Adapter>>
component "DocumentAdapter" as OutDocumentAdapter <<Out Adapter>>
component "TextEditorAdapter" as OutTextEditorAdapter <<Out Adapter>>
component "LoggerAdapter" as OutLoggerAdapter <<Out Adapter>>

extension.ts --> InWebviewAdapter : create
extension.ts --> InDocumentAdapter : create
extension.ts --> InTextEditorAdapter : create
extension.ts --> OutWebviewAdapter : set active webview
extension.ts --> OutDocumentAdapter : set active document

InWebviewAdapter --> InitWebviewUseCase
InWebviewAdapter --> SyncDocumentUseCase
InDocumentAdapter --> SyncWebviewUseCase
InTextEditorAdapter --> TextEditorUseCase

InitWebviewUseCase <.. InitWebviewService
SyncWebviewUseCase <.. SyncWebviewService
SyncDocumentUseCase <.. SyncDocumentService
TextEditorUseCase <.. TextEditorService

InitWebviewService --> WebviewPort
SyncWebviewService --> WebviewPort
SyncWebviewService --> LoggerPort
SyncDocumentService --> DocumentPort
SyncDocumentService --> LoggerPort
TextEditorService --> TextEditorPort

WebviewPort <.. OutWebviewAdapter
DocumentPort <.. OutDocumentAdapter
TextEditorPort <.. OutTextEditorAdapter
LoggerPort <.. OutLoggerAdapter

@enduml
